Helps fix #26 by making them optional dependencies
To ensure a delightful user experience, this commit adds
to `extras_require` for graphviz and networkx. This will mean
that users will have to do pip install sf-hamilton[visualization]
to be able to get a DAG visualized.

Rather than doing a major version bump, we're doing a minor one;
this shouldn't break any body's core use, since they shouldn't be
visualizing the DAG in production each time.

Otherwise this updates the docs with this information.

Adjusts behavior when graphivz or networkx aren't present

Rather than causing an execute to fail, we'll instead log the
error and return early.

The message to the user should look something like:

```
ERROR:hamilton.graph: graphviz is required for visualizing the function graph. Install it with:

  pip install sf-hamilton[visualization] or pip install graphviz

Traceback (most recent call last):
  File "/Users/stefankrawczyk/temp/hamilton/hamilton/graph.py", line 142, in display
    import graphviz
ModuleNotFoundError: No module named 'graphviz'
```